ARG ALEPH_TAG
FROM ghcr.io/DilLDN25/op_aleph-ui-base:sha-${ALEPH_TAG} AS builder
LABEL org.opencontainers.image.source = "https://github.com/DilLDN25/op_aleph/ui"

RUN npm run messages
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /alephui/build /assets
